const AI_ENDPOINT='https://valedouro-mestre.tech-gandra.workers.dev';
const state={characters:[],active:0,history:[],pendingCheck:null,hiddenQuest:null,voice:false};
const creationRolls={},slotModes={};
const abilities=['FOR','DES','CON','INT','SAB','CAR'];
const labels={FOR:'Força',DES:'Destreza',CON:'Constituição',INT:'Inteligência',SAB:'Sabedoria',CAR:'Carisma'};
const hitDie={Barbaro:12,'Bárbaro':12,Guerreiro:10,Ranger:10,Patrulheiro:10,Paladino:10,'Clérigo':8,Druida:8,Monge:8,Ladino:8,Bardo:8,Bruxo:8,Feiticeiro:6,Mago:6};
function $(id){return document.getElementById(id)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id!=='opening')checkAI()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mod(v){return Math.floor((Number(v||10)-10)/2)}
function fmt(n){return (n>=0?'+':'')+n}
function prof(level){return 2+Math.floor((Math.max(1,level)-1)/4)}
function armorCA(type,dex,shield){let ca=10+dex;if(type==='Couro')ca=11+dex;if(type==='Camisão de malha')ca=13+Math.min(dex,2);if(type==='Cota de malha')ca=16;if(type==='Placas')ca=18;if(shield)ca+=2;return ca}
function classHP(classes,con){let hp=0;classes.forEach((c,ci)=>{const d=hitDie[c.name]||8;for(let i=0;i<c.level;i++)hp+=(ci===0&&i===0?d:Math.floor(d/2)+1)+con});return Math.max(1,hp)}
function calc(c){const level=c.classes.reduce((a,x)=>a+x.level,0),dex=mod(c.attrs.DES),con=mod(c.attrs.CON);c.level=level;c.prof=prof(level);c.ini=dex;c.ca=armorCA(c.armor,dex,c.shield);c.hpMax=classHP(c.classes,con);c.hp=c.hpMax;c.speed=9;c.hitDice=c.classes.map(x=>`${x.level}d${hitDie[x.name]||8}`).join(' + ');c.cls=c.classes.map(x=>`${x.name} ${x.level}`).join(' / ');return c}
function savedCharacters(){try{const x=JSON.parse(localStorage.getItem('valedouro.characters')||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveChars(){const existing=savedCharacters(),map=new Map(existing.map(c=>[`${c.name}|${c.cls}`,c]));state.characters.forEach(c=>map.set(`${c.name}|${c.cls}`,c));localStorage.setItem('valedouro.characters',JSON.stringify([...map.values()]))}
function classOpts(sel){return ['Guerreiro','Patrulheiro','Bárbaro','Paladino','Clérigo','Druida','Monge','Ladino','Bardo','Bruxo','Feiticeiro','Mago'].map(x=>`<option ${x===sel?'selected':''}>${x}</option>`).join('')}
function playerCount(){const n=+$('playerCount').value;$('charForms').innerHTML='';for(let i=0;i<n;i++){slotModes[i]='create';creationRolls[i]={index:0,attrs:{}};$('charForms').insertAdjacentHTML('beforeend',charSlot(i));renderSlot(i)}}
function charSlot(i){return `<div class="char-card" id="slot${i}"><div class="slot-head"><h3>Personagem ${i+1}</h3><div class="row"><button class="btn primary" id="modeCreate${i}" onclick="setSlotMode(${i},'create')">Criar nova ficha</button><button class="btn" id="modeLoad${i}" onclick="setSlotMode(${i},'load')">Carregar ficha salva</button></div></div><div id="slotBody${i}"></div></div>`}
function setSlotMode(i,mode){slotModes[i]=mode;document.querySelectorAll(`#slot${i} .slot-head .btn`).forEach(b=>b.classList.remove('primary'));$(mode==='create'?`modeCreate${i}`:`modeLoad${i}`).classList.add('primary');renderSlot(i)}
function renderSlot(i){slotModes[i]==='load'?renderLoadSlot(i):renderCreateSlot(i)}
function renderLoadSlot(i){const saved=savedCharacters(),body=$(`slotBody${i}`);if(!saved.length){body.innerHTML=`<div class="empty-state"><p>Nenhuma ficha salva neste navegador.</p><button class="btn" onclick="setSlotMode(${i},'create')">Criar personagem</button></div>`;return}body.innerHTML=`<div class="load-grid"><div class="field"><label>Ficha salva</label><select id="saved${i}" onchange="previewSaved(${i})">${saved.map((c,k)=>`<option value="${k}">${esc(c.name)} — ${esc(c.cls||'personagem')}</option>`).join('')}</select></div><div id="savedPreview${i}"></div></div>`;previewSaved(i)}
function previewSaved(i){const saved=savedCharacters(),c=saved[+$(`saved${i}`).value||0];$(`savedPreview${i}`).innerHTML=c?`<div class="saved-preview"><strong>${esc(c.name)}</strong><span>${esc(c.race)} • ${esc(c.cls)}</span><span>CA ${c.ca} • PV ${c.hpMax} • Nível ${c.level}</span></div>`:''}
function renderCreateSlot(i){const r=creationRolls[i]||{index:0,attrs:{}};creationRolls[i]=r;const complete=r.index>=abilities.length,current=abilities[Math.min(r.index,abilities.length-1)];$(`slotBody${i}`).innerHTML=`<div class="grid2"><div><div class="field"><label>Nome</label><input id="name${i}"></div><div class="field"><label>Povo</label><select id="race${i}"><option>Humano</option><option>Elfo</option><option>Anão</option><option>Halfling</option></select></div><div class="field"><label>Histórico</label><input id="bg${i}" value="Viajante"></div><div class="row"><div class="field"><label>Classe inicial</label><select id="c1${i}">${classOpts('Guerreiro')}</select></div><div class="field"><label>Nível</label><input id="l1${i}" type="number" min="1" max="20" value="1"></div></div><div class="row"><div class="field"><label>Multiclasse</label><select id="c2${i}"><option value="">— nenhuma —</option>${classOpts('Patrulheiro')}</select></div><div class="field"><label>Nível</label><input id="l2${i}" type="number" min="0" max="19" value="0"></div></div><div class="row"><div class="field"><label>Armadura</label><select id="armor${i}"><option>Nenhuma</option><option>Couro</option><option selected>Camisão de malha</option><option>Cota de malha</option><option>Placas</option></select></div><label class="checkline"><input id="shield${i}" type="checkbox"> Escudo</label></div></div><div><div class="attribute-builder"><div class="builder-head"><div><h4>Atributos</h4><p class="muted">4d6, descartando o menor. Os resultados não são digitados manualmente.</p></div><button class="btn small" onclick="resetAttributes(${i})">Reiniciar atributos</button></div><div class="ability-grid">${abilities.map(a=>`<div class="ability ${a===current&&!complete?'current':''}"><small>${labels[a]}</small><b>${r.attrs[a]??'—'}</b><span>${r.attrs[a]!=null?fmt(mod(r.attrs[a])):'aguardando'}</span></div>`).join('')}</div><div class="dice-workbench"><div class="roll-prompt">${complete?'Atributos concluídos.':`Role para <strong>${labels[current]}</strong>`}</div><div class="dice-tray">${r.lastDice?r.lastDice.map((d,k)=>`<div class="mini-d6 ${k===r.discardIndex?'discarded':''}">${d}</div>`).join(''):'<span class="muted">Os quatro d6 aparecerão aqui.</span>'}</div><button class="btn primary" onclick="rollAttribute(${i})" ${complete?'disabled':''}>${complete?'Atributos definidos':`🎲 Rolar 4d6 para ${labels[current]}`}</button>${r.lastTotal!=null?`<div class="roll-summary">Resultado anterior: ${r.lastDice.join(' + ')} → descarta ${r.lastDice[r.discardIndex]} → <strong>${r.lastTotal}</strong></div>`:''}</div></div></div></div>`}
function snapshotSlot(i){return {name:$(`name${i}`)?.value,race:$(`race${i}`)?.value,bg:$(`bg${i}`)?.value,c1:$(`c1${i}`)?.value,l1:$(`l1${i}`)?.value,c2:$(`c2${i}`)?.value,l2:$(`l2${i}`)?.value,armor:$(`armor${i}`)?.value,shield:$(`shield${i}`)?.checked}}
function restoreSlot(i,v){if(v.name==null)return;$(`name${i}`).value=v.name;$(`race${i}`).value=v.race;$(`bg${i}`).value=v.bg;$(`c1${i}`).value=v.c1;$(`l1${i}`).value=v.l1;$(`c2${i}`).value=v.c2;$(`l2${i}`).value=v.l2;$(`armor${i}`).value=v.armor;$(`shield${i}`).checked=v.shield}
function rollAttribute(i){const r=creationRolls[i];if(!r||r.index>=abilities.length)return;const vals=snapshotSlot(i),dice=Array.from({length:4},()=>Math.floor(Math.random()*6)+1);let min=0;for(let k=1;k<4;k++)if(dice[k]<dice[min])min=k;const total=dice.reduce((a,b)=>a+b,0)-dice[min],a=abilities[r.index];r.attrs[a]=total;r.lastDice=dice;r.discardIndex=min;r.lastTotal=total;r.index++;renderCreateSlot(i);restoreSlot(i,vals)}
function resetAttributes(i){const vals=snapshotSlot(i);creationRolls[i]={index:0,attrs:{}};renderCreateSlot(i);restoreSlot(i,vals)}
function collectChars(){const n=+$('playerCount').value,result=[],saved=savedCharacters();for(let i=0;i<n;i++){if(slotModes[i]==='load'){const c=saved[+$(`saved${i}`)?.value||0];if(!c)return alert(`Selecione uma ficha salva para o Personagem ${i+1}.`);result.push(JSON.parse(JSON.stringify(c)));continue}const r=creationRolls[i];if(!r||r.index<abilities.length)return alert(`Role os seis atributos do Personagem ${i+1}.`);const l1=Math.max(1,+$(`l1${i}`).value||1),c2=$(`c2${i}`).value,l2=+$(`l2${i}`).value||0;if(l1+l2>20)return alert(`O nível total do Personagem ${i+1} não pode ultrapassar 20.`);if(c2&&c2===$(`c1${i}`).value)return alert(`Escolha classes diferentes para o Personagem ${i+1}.`);const name=$(`name${i}`).value.trim();if(!name)return alert(`Informe o nome do Personagem ${i+1}.`);const classes=[{name:$(`c1${i}`).value,level:l1}];if(c2&&l2>0)classes.push({name:c2,level:l2});result.push(calc({name,race:$(`race${i}`).value,background:$(`bg${i}`).value,classes,attrs:{...r.attrs},armor:$(`armor${i}`).value,shield:$(`shield${i}`).checked}))}state.characters=result;saveChars();showReview()}
function sheet(c){return `<h2>${esc(c.name)}</h2><p>${esc(c.race)} • <strong>${esc(c.cls)}</strong> • nível total ${c.level}</p><div class="stat-grid"><div class="stat">CA<b>${c.ca}</b></div><div class="stat">PV<b>${c.hp}/${c.hpMax}</b></div><div class="stat">Iniciativa<b>${fmt(c.ini)}</b></div><div class="stat">Proficiência<b>${fmt(c.prof)}</b></div><div class="stat">Deslocamento<b>${c.speed} m</b></div><div class="stat">Dados de Vida<b style="font-size:15px">${esc(c.hitDice)}</b></div></div><div class="ability-grid">${abilities.map(a=>`<div class="ability"><small>${labels[a]}</small><b>${c.attrs[a]}</b><span>${fmt(mod(c.attrs[a]))}</span></div>`).join('')}</div><div class="sheet-cols"><div class="sheet-section"><h4>Classes</h4><p>${c.classes.map(x=>`${esc(x.name)} ${x.level}`).join(' / ')}</p><p><strong>Armadura:</strong> ${esc(c.armor)} ${c.shield?'+ escudo':''}</p></div><div class="sheet-section"><h4>Identidade</h4><p><strong>Povo:</strong> ${esc(c.race)}</p><p><strong>Histórico:</strong> ${esc(c.background||'—')}</p></div></div>`}
function openSheet(i){$('sheetContent').innerHTML=sheet(state.characters[i]);$('sheetModal').classList.add('active')}
function closeSheet(){$('sheetModal').classList.remove('active')}
function showReview(){$('reviewCards').innerHTML=state.characters.map((c,i)=>`<div class="char-card">${sheet(c)}<button class="btn" onclick="openSheet(${i})">Abrir ficha</button></div>`).join('');show('review')}
function showLibrary(){state.characters=savedCharacters();$('library').innerHTML=state.characters.length?state.characters.map((c,i)=>`<div class="char-card"><h3>${esc(c.name)}</h3><p>${esc(c.cls)}</p><p>CA ${c.ca} • PV ${c.hpMax}</p><button class="btn" onclick="openSheet(${i})">Ficha</button></div>`).join(''):'<p class="muted">Nenhum personagem salvo neste navegador.</p>';show('characters')}
function selectPC(i){state.active=i;document.querySelectorAll('.pc').forEach((x,j)=>x.classList.toggle('selected',i===j));$('activeName').textContent=state.characters[i]?.name||'—'}
function renderParty(){$('party').innerHTML=state.characters.map((c,i)=>`<div class="pc ${i===state.active?'selected':''}" onclick="selectPC(${i})"><strong>${esc(c.name)}</strong><small>${esc(c.cls)}</small><small>CA ${c.ca} • PV ${c.hp}/${c.hpMax}</small></div>`).join('')}
function addStory(html,cls=''){const d=document.createElement('div');d.className=`entry ${cls}`;d.innerHTML=html;$('story').appendChild(d);$('story').scrollTop=$('story').scrollHeight;return d}
async function loadHiddenQuest(){try{const idx=await fetch('data/quests-index.json').then(r=>r.json()),q=idx.find(x=>(x.level?.min??1)<=1&&(x.level?.max??99)>=1)||idx[0];if(q)state.hiddenQuest=await fetch(`data/quests/${q.id}/quest.json`).then(r=>r.json())}catch(e){console.warn('Quest interna indisponível',e);state.hiddenQuest=null}}
async function startAdventure(){if(!state.characters.length)return alert('Crie pelo menos um personagem.');state.active=0;state.history=[];state.pendingCheck=null;renderParty();selectPC(0);$('story').innerHTML='';$('rollbox').classList.remove('active');show('game');await loadHiddenQuest();await askAI('Inicie a sessão. Apresente uma cena inicial natural para o grupo e convide os jogadores a agir. Não revele estruturas internas, IDs, quests ou menus de missão.')}
async function checkAI(){try{const r=await fetch(AI_ENDPOINT),d=await r.json(),ok=r.ok&&d.ok===true;$('aiStatus').textContent=ok?'IA: conectada':'IA: requer configuração';$('aiStatus').classList.toggle('ok',ok)}catch{$('aiStatus').textContent='IA: indisponível';$('aiStatus').classList.remove('ok')}}
function partyForAI(){return state.characters.map(c=>({name:c.name,race:c.race,background:c.background,classes:c.classes,attributes:c.attrs,armor:c.armor,shield:c.shield,ca:c.ca,hp:c.hp,hpMax:c.hpMax}))}
async function act(){if(state.pendingCheck)return alert('Resolva a rolagem solicitada pelo Mestre antes de agir.');const t=$('action').value.trim(),p=state.characters[state.active];if(!t)return;addStory(`<b>${esc(p.name)}:</b> ${esc(t)}`);const tagged=`${p.name} declara: ${t}`;state.history.push({role:'user',content:tagged});$('action').value='';await askAI(tagged)}
async function askAI(action){$('actBtn').disabled=true;const wait=addStory('<b>Mestre:</b> pensando…','master');try{const active=state.characters[state.active],payload={action,player:{active_character:active?.name,party:partyForAI()},quest:state.hiddenQuest,world:{rule:'quests_hidden_from_player',multiplayer:state.characters.length>1},history:state.history};const r=await fetch(AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Falha na IA');wait.remove();const text=d.reply||'';state.history.push({role:'assistant',content:text});const clean=text.replace(/\[\[ROLL:[^\]]+\]\]/g,'').trim();addStory(`<b>Mestre:</b> ${esc(clean).replace(/\n/g,'<br>')}`,'master');const m=text.match(/\[\[ROLL:(FOR|DES|CON|INT|SAB|CAR):(\d+):([^\]]+)\]\]/);if(m)requestRoll(m[1],+m[2],m[3])}catch(e){wait.innerHTML=`<b>Mestre:</b> <span class="fail">IA indisponível: ${esc(e.message)}</span>`}finally{$('actBtn').disabled=!!state.pendingCheck}}
function requestRoll(attr,cd,motivo){const p=state.characters[state.active];state.pendingCheck={attr,cd,motivo,playerIndex:state.active};$('rollbox').classList.add('active');$('rollText').innerHTML=`<strong>${esc(p.name)}</strong>: teste de ${labels[attr]} (${attr}), CD ${cd}<br><span class="muted">${esc(motivo)}</span>`;$('die').textContent='d20';$('rollResult').innerHTML='';$('rollBtn').disabled=false}
async function rollCheck(){const r=state.pendingCheck;if(!r)return;const p=state.characters[r.playerIndex],d20=1+Math.floor(Math.random()*20),bonus=mod(p.attrs[r.attr]),total=d20+bonus,success=total>=r.cd;$('die').textContent=d20;$('rollResult').innerHTML=`${esc(p.name)}: ${r.attr} ${fmt(bonus)} = <strong>${total}</strong> vs CD ${r.cd} — <span class="${success?'pass':'fail'}">${success?'SUCESSO':'FALHA'}</span>`;$('rollBtn').disabled=true;addStory(`<b>Rolagem de ${esc(p.name)}:</b> d20 ${d20} ${fmt(bonus)} = ${total} vs CD ${r.cd} — ${success?'SUCESSO':'FALHA'}`,'system');const msg=`Resultado do teste solicitado para ${p.name}: ${r.attr}, d20=${d20}, modificador=${bonus}, total=${total}, CD=${r.cd}, resultado=${success?'sucesso':'falha'}, motivo=${r.motivo}. Narre a consequência e continue a cena.`;state.history.push({role:'user',content:msg});state.pendingCheck=null;setTimeout(()=>$('rollbox').classList.remove('active'),1000);await askAI(msg)}
function quickDie(){const sides=+$('dieType').value,n=1+Math.floor(Math.random()*sides);$('quickResult').textContent=`d${sides}: ${n}`}
function resumeGame(){const saved=savedCharacters();if(!saved.length)return alert('Não há personagens salvos.');state.characters=[JSON.parse(JSON.stringify(saved[0]))];startAdventure()}
window.addEventListener('DOMContentLoaded',()=>{playerCount();checkAI()});
