(function(){
const KEY='valedouro.injuries.v1';
const severity={superficial:{maxBlock:0,recovery:'1–5 dias'},moderate:{maxBlock:.15,recovery:'dias a 2–3 semanas'},grave:{maxBlock:.30,recovery:'semanas ou meses'},critical:{maxBlock:.60,recovery:'prolongada'}};
const stages=['active','stabilized','treatment','recovering','resolved','sequela'];
function charKey(c){return `${c.name}|${c.cls||''}`}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function save(db){localStorage.setItem(KEY,JSON.stringify(db))}
function ensure(c){const db=load(),k=charKey(c);if(!db[k])db[k]={injuries:[],conditions:[],updatedAt:new Date().toISOString()};c.healthState=db[k];recalc(c);save(db);return db[k]}
function persist(c){const db=load(),k=charKey(c);db[k]=c.healthState||ensure(c);db[k].updatedAt=new Date().toISOString();save(db);if(typeof window.saveChars==='function')window.saveChars()}
function recalc(c){const hs=c.healthState||{injuries:[]};const original=Math.max(1,Number(c.hpMaxOriginal||c.hpMax||1));c.hpMaxOriginal=original;const active=(hs.injuries||[]).filter(x=>!['resolved'].includes(x.stage));let block=active.reduce((sum,x)=>sum+Math.max(0,Number(x.hpBlock||0)),0);block=Math.min(original-1,block);c.hpFunctionalMax=Math.max(1,original-block);c.hp=Math.min(Number(c.hp||original),c.hpFunctionalMax);return c.hpFunctionalMax}
function add(c,data){const hs=ensure(c),sev=severity[data.severity]||severity.superficial,original=Math.max(1,Number(c.hpMaxOriginal||c.hpMax||1));const requested=data.hpBlock==null?Math.round(original*sev.maxBlock):Number(data.hpBlock);const injury={id:data.id||`inj-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:data.name||'Ferimento',location:data.location||'',severity:data.severity||'superficial',stage:data.stage||'active',hpBlock:Math.max(0,requested),limitation:data.limitation||'',bleeding:data.bleeding||'none',createdAt:new Date().toISOString(),treatedAt:null,recoveryHours:Number(data.recoveryHours||0),elapsedRecoveryHours:0,notes:data.notes||''};hs.injuries.push(injury);recalc(c);persist(c);return injury}
function get(c,id){return ensure(c).injuries.find(x=>x.id===id)}
function stabilize(c,id,level='full'){const x=get(c,id);if(!x)return false;x.stage='stabilized';x.bleeding=level==='partial'?'partial':'stabilized';persist(c);return true}
function startTreatment(c,id,opts={}){const x=get(c,id);if(!x)return false;x.stage='treatment';x.treatedAt=new Date().toISOString();if(opts.recoveryHours!=null)x.recoveryHours=Number(opts.recoveryHours);persist(c);return true}
function resolve(c,id,sequela=''){const x=get(c,id);if(!x)return false;x.stage=sequela?'sequela':'resolved';x.sequela=sequela||'';x.hpBlock=sequela?Math.max(0,Number(x.hpBlock||0)):0;recalc(c);persist(c);return true}
function advanceTime(c,hours){const hs=ensure(c),h=Math.max(0,Number(hours)||0);let hpLoss=0;hs.injuries.forEach(x=>{if(x.bleeding==='active'&&x.severity==='critical')hpLoss+=2*h;else if(x.bleeding==='partial')hpLoss+=1*h;if(['treatment','recovering'].includes(x.stage)){x.stage='recovering';x.elapsedRecoveryHours=(x.elapsedRecoveryHours||0)+h;if(x.recoveryHours>0&&x.elapsedRecoveryHours>=x.recoveryHours){x.stage='resolved';x.hpBlock=0;}}});if(hpLoss)c.hp=Math.max(0,Number(c.hp||0)-hpLoss);recalc(c);persist(c);return {hpLoss,hp:c.hp,functionalMax:c.hpFunctionalMax}}
function applyHealingMagic(c,hp){ensure(c);const before=Number(c.hp||0);c.hp=Math.min(c.hpFunctionalMax, before+Math.max(0,Number(hp)||0));persist(c);return c.hp-before}
function firstAid(c,id,{trained=false,medicalTraining=false,result='success',useKit=false}={}){ensure(c);const inv=window.ValeInventory?.ensure(c);let kit=null;if(inv)kit=[...(inv.items||[])].find(x=>x.id==='first-aid-kit');if(useKit){if(!kit||Number(kit.qty||0)<=0)return {ok:false,reason:'no-kit'};window.ValeInventory.consume(c,'first-aid-kit',1)}if(medicalTraining&&result==='auto')result=Math.random()<.9?'success':'fail';if(result==='success'){stabilize(c,id,'full');return {ok:true,status:'stabilized'}}if(result==='partial'){stabilize(c,id,'partial');return {ok:true,status:'partial'}}return {ok:false,status:'active'}}
function herbalAid(c,id,resourceId,result='success'){ensure(c);if(!window.ValeInventory?.consume(c,resourceId,1))return {ok:false,reason:'resource'};if(result==='success'){const x=get(c,id);if(x&&x.severity!=='critical')x.stage='stabilized';persist(c);return {ok:true}}return {ok:false}}
function summary(c){ensure(c);return {hp:Number(c.hp||0),functionalMax:c.hpFunctionalMax,originalMax:c.hpMaxOriginal,injuries:c.healthState.injuries.filter(x=>x.stage!=='resolved'),conditions:c.healthState.conditions||[]}}
window.ValeInjuries={severity,stages,ensure,persist,recalc,add,get,stabilize,startTreatment,resolve,advanceTime,applyHealingMagic,firstAid,herbalAid,summary};
})();