(function(){
'use strict';
const KEY='valedouro.inventory.v2',LEGACY='valedouro.inventory.v1',EVENT_KEY='valedouro.inventory.events.v1';
const travelerKit=[
{id:'backpack',name:'Mochila',qty:1,unit:'un',category:'Equipamento',state:'available',container:true},{id:'canteen',name:'Cantil',qty:1,unit:'un',category:'Equipamento',state:'available',container:true,fillable:'water',capacity:1},{id:'blanket',name:'Manta de viagem',qty:1,unit:'un',category:'Equipamento',state:'available'},{id:'cloak',name:'Capa de viagem',qty:1,unit:'un',category:'Equipamento',state:'available'},{id:'flint-steel',name:'Pederneira e aço',qty:1,unit:'conj.',category:'Ferramenta',state:'available'},{id:'torch',name:'Tocha',qty:3,unit:'un',category:'Consumível',state:'available',consumable:true},{id:'rope',name:'Corda comum',qty:10,unit:'m',category:'Material',state:'available',fractionable:true},{id:'rations',name:'Rações de viagem',qty:3,unit:'dias',category:'Consumível',state:'available',consumable:true},{id:'cookware',name:'Panela/caneca metálica',qty:1,unit:'un',category:'Equipamento',state:'available'},{id:'cutlery',name:'Talheres simples',qty:1,unit:'conj.',category:'Equipamento',state:'available'},{id:'cloth',name:'Pano de tecido',qty:2,unit:'un',category:'Material',state:'available',consumable:true},{id:'soap',name:'Sabão pequeno',qty:1,unit:'un',category:'Consumível',state:'available',consumable:true},{id:'waterskin',name:'Recipiente auxiliar',qty:1,unit:'un',category:'Equipamento',state:'available',container:true,fillable:'water',capacity:1},{id:'small-bag',name:'Pequeno saco',qty:2,unit:'un',category:'Equipamento',state:'available',container:true},{id:'candle',name:'Vela',qty:2,unit:'un',category:'Consumível',state:'available',consumable:true},{id:'chalk',name:'Giz',qty:3,unit:'un',category:'Consumível',state:'available',consumable:true},{id:'utility-knife',name:'Faca utilitária',qty:1,unit:'un',category:'Ferramenta',state:'available',tool:true}
];
const firstAidKit={id:'first-aid-kit',name:'Kit de Primeiros Socorros',qty:5,unit:'usos',category:'Médico',state:'available',maxQty:5,specialized:true,consumable:true};
const basePrices={torch:2,rope:2,rations:8,cloth:3,soap:4,candle:1,chalk:1,canteen:20,blanket:30,cloak:50,backpack:40,'utility-knife':20,'first-aid-kit-use':15};
const clone=x=>JSON.parse(JSON.stringify(x)); const key=c=>`${c.name}|${c.cls||''}`; const esc=s=>window.esc?window.esc(String(s)):String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{let raw=localStorage.getItem(KEY);if(!raw){raw=localStorage.getItem(LEGACY);if(raw)localStorage.setItem(KEY,raw)}return JSON.parse(raw||'{}')}catch{return {}}} function saveAll(x){localStorage.setItem(KEY,JSON.stringify(x))}
function isRanger(c){return (c.classes||[]).some(x=>/ranger|patrulheiro/i.test(x.name||''))||/ranger|patrulheiro/i.test(c.cls||'')}
function normalizeItem(x){return {state:'available',category:'Item',...x,qty:Number(x.qty||0)}}
function ensure(c){const db=load(),k=key(c);if(!db[k])db[k]={version:2,coins:{gold:0,silver:10,copper:0},items:clone(travelerKit),resources:[],history:[],loadState:'normal',updatedAt:new Date().toISOString()};const inv=db[k];inv.version=2;inv.items=(inv.items||[]).map(normalizeItem);inv.resources=(inv.resources||[]).map(normalizeItem);inv.history=inv.history||[];inv.loadState=inv.loadState||'normal';if(isRanger(c)&&!inv.items.find(x=>x.id==='first-aid-kit'))inv.items.push(clone(firstAidKit));saveAll(db);c.inventory=inv;return inv}
function persist(c){const db=load(),k=key(c);db[k]=c.inventory||ensure(c);db[k].updatedAt=new Date().toISOString();saveAll(db);if(typeof window.saveChars==='function')window.saveChars();window.dispatchEvent(new CustomEvent('valedouro:inventory-change',{detail:{character:c.name}}))}
function all(inv){return [...(inv.items||[]),...(inv.resources||[])]} function find(inv,id){return all(inv).find(x=>x.id===id)} function listFor(inv,it){return (inv.resources||[]).includes(it)?inv.resources:inv.items}
function record(c,type,data={}){const inv=ensure(c);inv.history.unshift({at:new Date().toISOString(),type,...data});inv.history=inv.history.slice(0,100)}
function add(c,item){const inv=ensure(c),list=item.resource?inv.resources:inv.items,found=list.find(x=>x.id===item.id&&x.state!=='lost');if(found)found.qty+=Number(item.qty||1);else list.push(normalizeItem({...item,qty:Number(item.qty||1)}));record(c,'add',{item:item.id,qty:Number(item.qty||1)});persist(c);return true}
function consume(c,id,qty=1){qty=Number(qty);const inv=ensure(c),it=find(inv,id);if(!it||it.state==='lost'||it.state==='loaned'||Number(it.qty)<qty||qty<=0)return false;it.qty=Math.max(0,it.qty-qty);record(c,'consume',{item:id,qty});persist(c);return true}
function setQty(c,id,qty){const inv=ensure(c),it=find(inv,id);if(!it)return false;it.qty=Math.max(0,Number(qty)||0);persist(c);return true}
function setState(c,id,state,note=''){const inv=ensure(c),it=find(inv,id);if(!it)return false;it.state=state||'available';it.stateNote=note;record(c,'state',{item:id,state:it.state,note});persist(c);return true}
function split(c,id,qty,newName){qty=Number(qty);const inv=ensure(c),it=find(inv,id);if(!it?.fractionable||qty<=0||qty>=it.qty)return false;it.qty-=qty;const piece={...clone(it),id:`${id}-piece-${Date.now()}`,name:newName||`Pedaço de ${it.name}`,qty,state:'available'};listFor(inv,it).push(piece);record(c,'split',{item:id,qty,newItem:piece.id});persist(c);return piece}
function remove(c,id,qty=1,reason='abandoned'){const inv=ensure(c),it=find(inv,id);if(!it||qty<=0||it.qty<qty)return false;it.qty-=qty;if(it.qty<=0){it.qty=0;it.state=reason==='lost'?'lost':'abandoned'}record(c,reason,{item:id,qty});persist(c);return true}
function transfer(from,to,id,qty=1){const inv=ensure(from),it=find(inv,id);qty=Number(qty);if(!it||it.state!=='available'||qty<=0||it.qty<qty)return false;const copy={...clone(it),qty,state:'available',resource:(inv.resources||[]).includes(it)};it.qty-=qty;record(from,'transfer-out',{item:id,qty,to:to.name});persist(from);add(to,copy);record(to,'transfer-in',{item:id,qty,from:from.name});persist(to);return true}
function walletCopper(coins){return (coins.gold||0)*100+(coins.silver||0)*10+(coins.copper||0)} function normalizeCoins(total){total=Math.max(0,Math.floor(total));return {gold:Math.floor(total/100),silver:Math.floor(total%100/10),copper:total%10}} function pay(c,copper){const inv=ensure(c),total=walletCopper(inv.coins);if(total<Number(copper))return false;inv.coins=normalizeCoins(total-Number(copper));record(c,'pay',{copper:Number(copper)});persist(c);return true} function credit(c,copper){const inv=ensure(c);inv.coins=normalizeCoins(walletCopper(inv.coins)+Math.max(0,Number(copper)||0));record(c,'credit',{copper:Number(copper)||0});persist(c);return true}
function priceOf(id,qty=1,multiplier=1){return Math.ceil((basePrices[id]||0)*Number(qty||1)*Number(multiplier||1))} function buy(c,item,qty=1,multiplier=1){const cost=priceOf(item.id,qty,multiplier);if(!cost||!pay(c,cost))return {ok:false,cost};add(c,{...item,qty});return {ok:true,cost}} function sell(c,id,qty=1,rate=.5){const inv=ensure(c),it=find(inv,id),value=Math.floor(priceOf(id,qty,1)*Math.max(.4,Math.min(.6,rate)));if(!it||!value||!remove(c,id,qty,'sold'))return {ok:false,value};credit(c,value);return {ok:true,value}}
function kitDeficit(c){const inv=ensure(c);return travelerKit.map(std=>({...std,current:find(inv,std.id)?.qty||0,missing:Math.max(0,std.qty-(find(inv,std.id)?.qty||0))})).filter(x=>x.missing>0)} function marketQuote(c,availability=null,multiplier=1){return kitDeficit(c).filter(x=>!availability||availability.includes(x.id)).map(x=>({...x,priceCopper:basePrices[x.id]==null?null:priceOf(x.id,x.missing,multiplier)}))} function replenish(c,ids,availability=null,multiplier=1){const quote=marketQuote(c,availability,multiplier).filter(x=>!ids||ids.includes(x.id)),priced=quote.filter(x=>x.priceCopper!=null),cost=priced.reduce((a,x)=>a+x.priceCopper,0);if(!pay(c,cost))return {ok:false,reason:'funds',cost};priced.forEach(x=>setQty(c,x.id,x.qty));return {ok:true,cost,items:priced}}
function replenishFirstAid(c,uses,costPerUse=basePrices['first-aid-kit-use']){const inv=ensure(c),kit=find(inv,'first-aid-kit');if(!kit)return {ok:false,reason:'no-kit'};const addUses=Math.min(Math.max(0,Number(uses)||0),5-kit.qty),cost=addUses*costPerUse;if(cost&&!pay(c,cost))return {ok:false,reason:'funds',cost};kit.qty+=addUses;record(c,'medical-replenish',{uses:addUses,cost});persist(c);return {ok:true,uses:addUses,cost}}
function gather(c,resource){return add(c,{id:resource.id||('resource-'+Date.now()),name:resource.name,qty:resource.qty||1,unit:resource.unit||'un',category:'Recurso natural',resource:true,source:resource.source||'nature',quality:resource.quality||'unknown',state:'available'})}
function moneyText(coins){return `${coins.gold||0} ouro • ${coins.silver||0} prata • ${coins.copper||0} cobre`} function loadState(c,state){const inv=ensure(c);inv.loadState=['normal','heavy','overloaded'].includes(state)?state:'normal';persist(c)}
function eventSeen(id){if(!id)return false;try{return JSON.parse(localStorage.getItem(EVENT_KEY)||'[]').includes(id)}catch{return false}} function markEvent(id){if(!id)return;let a=[];try{a=JSON.parse(localStorage.getItem(EVENT_KEY)||'[]')}catch{};a.push(id);localStorage.setItem(EVENT_KEY,JSON.stringify([...new Set(a)].slice(-500)))}
function applyEvent(c,e){if(!e||eventSeen(e.eventId))return {ok:false,reason:'duplicate'};let ok=false;switch(e.action){case'consume':ok=consume(c,e.itemId,e.qty);break;case'add':ok=add(c,e.item);break;case'pay':ok=pay(c,e.copper);break;case'credit':ok=credit(c,e.copper);break;case'state':ok=setState(c,e.itemId,e.state,e.note);break;case'abandon':ok=remove(c,e.itemId,e.qty,'abandoned');break;case'lost':ok=remove(c,e.itemId,e.qty,'lost');break;}if(ok)markEvent(e.eventId);return {ok:!!ok}}
function actionButton(label,fn){return `<button class="btn small" onclick="${fn}">${label}</button>`} function renderActions(c,it){const idx=window.state?.characters?.indexOf(c)??0,id=JSON.stringify(it.id);let a=[];if(it.consumable&&it.qty>0)a.push(actionButton('Consumir',`ValeInventory.uiConsume(${idx},${id})`));if(it.state==='available'&&!it.consumable)a.push(actionButton('Usar',`ValeInventory.uiState(${idx},${id},'in-use')`));if(it.state==='in-use'||it.state==='equipped')a.push(actionButton('Guardar',`ValeInventory.uiState(${idx},${id},'available')`));if(it.fractionable&&it.qty>1)a.push(actionButton('Cortar',`ValeInventory.uiSplit(${idx},${id})`));if(it.qty>0)a.push(actionButton('Abandonar',`ValeInventory.uiAbandon(${idx},${id})`));return a.join(' ')}
function open(i){const c=window.state?.characters?.[i??window.state.active];if(!c)return;const inv=ensure(c),groups={};all(inv).filter(x=>x.qty>0&&x.state!=='lost'&&x.state!=='abandoned').forEach(x=>(groups[x.category||'Item']??=[]).push(x));const rows=Object.entries(groups).map(([g,items])=>`<tr><th colspan="4">${esc(g)}</th></tr>`+items.map(x=>`<tr><td>${esc(x.name)}${x.state!=='available'?`<div class="muted">${esc(x.state)}${x.stateNote?' — '+esc(x.stateNote):''}</div>`:''}</td><td>${x.qty}${x.maxQty?'/'+x.maxQty:''} ${esc(x.unit||'')}</td><td>${esc(x.source||'—')}</td><td>${renderActions(c,x)}</td></tr>`).join('')).join('');const health=window.ValeInjuries?.summary(c),injury=health?.injuries?.length?`<p><strong>Ferimentos ativos:</strong> ${health.injuries.length} • HP funcional ${health.hp}/${health.functionalMax}</p>`:'';document.getElementById('inventoryContent').innerHTML=`<h2>Inventário — ${esc(c.name)}</h2><p><strong>Bolsa:</strong> ${moneyText(inv.coins)} &nbsp; <strong>Carga:</strong> ${inv.loadState==='normal'?'Normal':inv.loadState==='heavy'?'Pesada':'Sobrecarga'}</p>${injury}<table class="inventory-table"><thead><tr><th>Item</th><th>Quantidade</th><th>Origem</th><th>Ações</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Inventário vazio.</td></tr>'}</tbody></table><p class="muted">PO/PA/PC = 1:10:100. Recursos são finitos; recipientes, disponibilidade e contexto determinam o que pode ser transportado ou reabastecido.</p>`;document.getElementById('inventoryModal').classList.add('active')}
function refresh(i){open(i)} function uiConsume(i,id){const c=state.characters[i];if(consume(c,id,1))refresh(i)} function uiState(i,id,s){const c=state.characters[i];if(setState(c,id,s))refresh(i)} function uiSplit(i,id){const c=state.characters[i],it=find(ensure(c),id),raw=prompt(`Quanto de ${it?.name||'item'} deseja separar?`),q=Number(String(raw||'').replace(',','.'));if(split(c,id,q))refresh(i)} function uiAbandon(i,id){const c=state.characters[i];if(confirm('Abandonar uma unidade/medida deste item?')&&remove(c,id,1,'abandoned'))refresh(i)} function close(){document.getElementById('inventoryModal')?.classList.remove('active')}
function publicState(){return (window.state?.characters||[]).map(c=>{const inv=ensure(c);return {name:c.name,coins:inv.coins,loadState:inv.loadState,items:all(inv).filter(x=>x.qty>0).map(x=>({id:x.id,name:x.name,qty:x.qty,unit:x.unit,state:x.state,category:x.category}))}})}
window.ValeInventory={travelerKit,firstAidKit,basePrices,ensure,persist,add,consume,setQty,setState,split,remove,transfer,pay,credit,buy,sell,kitDeficit,marketQuote,replenish,replenishFirstAid,gather,moneyText,loadState,applyEvent,publicState,open,close,uiConsume,uiState,uiSplit,uiAbandon};window.openInventory=open;window.closeInventory=close;
})();