(function(){
'use strict';
const KEY='valedouro.memory.v1';
const EVENT_KEY='valedouro.memory.events.v1';
const VERSION=1;
const RELATION_LABELS=[[-60,'Hostil'],[-20,'Desconfiado'],[20,'Neutro'],[60,'Favorável'],[101,'Aliado']];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const now=()=>new Date().toISOString();
const uid=(p='mem')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
function blank(){return {version:VERSION,facts:[],npcs:{},factions:{},locations:{},commitments:[],secrets:[],updatedAt:null};}
function load(){try{return {...blank(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return blank()}}
function save(db){db.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(db));return db}
function seen(id){if(!id)return false;try{return JSON.parse(localStorage.getItem(EVENT_KEY)||'[]').includes(id)}catch{return false}}
function mark(id){if(!id)return;let a=[];try{a=JSON.parse(localStorage.getItem(EVENT_KEY)||'[]')}catch{};a.push(id);localStorage.setItem(EVENT_KEY,JSON.stringify([...new Set(a)].slice(-1000)))}
function relationLabel(v){v=clamp(Number(v)||0,-100,100);for(const [max,label] of RELATION_LABELS)if(v<max)return label;return 'Aliado'}
function ensureNpc(db,npc={}){const id=npc.npcId||npc.id||uid('npc');if(!db.npcs[id])db.npcs[id]={npcId:id,name:npc.name||'NPC',role:npc.role||'',locationId:npc.locationId||null,factionId:npc.factionId||null,status:npc.status||'active',groupRelation:{affinity:0,trust:0},characterRelations:{},knownFacts:[],encounters:[],history:[],importance:npc.importance||'medium'};Object.assign(db.npcs[id],Object.fromEntries(Object.entries(npc).filter(([,v])=>v!==undefined)));return db.npcs[id]}
function ensureFaction(db,f={}){const id=f.factionId||f.id||uid('fac');if(!db.factions[id])db.factions[id]={factionId:id,name:f.name||'Facção',reputation:0,history:[]};return db.factions[id]}
function ensureLocation(db,l={}){const id=l.locationId||l.id||uid('loc');if(!db.locations[id])db.locations[id]={locationId:id,name:l.name||'Local',state:{},history:[]};return db.locations[id]}
function addFact(fact={}){const db=load(),id=fact.memoryId||fact.id||uid('fact');if(db.facts.some(x=>x.memoryId===id))return db.facts.find(x=>x.memoryId===id);const item={memoryId:id,text:String(fact.text||''),importance:fact.importance||'medium',scope:fact.scope||'witnessed',questId:fact.questId||window.state?.campaign?.currentQuestId||null,npcIds:Array.isArray(fact.npcIds)?fact.npcIds:[],characterIds:Array.isArray(fact.characterIds)?fact.characterIds:[],factionIds:Array.isArray(fact.factionIds)?fact.factionIds:[],locationIds:Array.isArray(fact.locationIds)?fact.locationIds:[],public:fact.public===true,secret:fact.secret===true,createdAt:now()};db.facts.push(item);item.npcIds.forEach(nid=>{const n=ensureNpc(db,{npcId:nid});if(!n.knownFacts.includes(id))n.knownFacts.push(id)});save(db);return item}
function registerNpc(npc={}){const db=load(),n=ensureNpc(db,npc);save(db);return n}
function encounter(npcId,data={}){const db=load(),n=ensureNpc(db,{npcId,name:data.name});n.encounters.push({at:now(),questId:data.questId||window.state?.campaign?.currentQuestId||null,locationId:data.locationId||null,summary:data.summary||''});n.lastEncounterAt=now();if(data.status)n.status=data.status;save(db);return n}
function adjustNpc(npcId,delta={},meta={}){const db=load(),n=ensureNpc(db,{npcId,name:meta.name});const rel=n.groupRelation||(n.groupRelation={affinity:0,trust:0});rel.affinity=clamp((Number(rel.affinity)||0)+(Number(delta.affinity)||0),-100,100);rel.trust=clamp((Number(rel.trust)||0)+(Number(delta.trust)||0),-100,100);if(meta.characterId){const cr=n.characterRelations[meta.characterId]||(n.characterRelations[meta.characterId]={affinity:0,trust:0});cr.affinity=clamp(cr.affinity+(Number(delta.affinity)||0),-100,100);cr.trust=clamp(cr.trust+(Number(delta.trust)||0),-100,100)}n.history.push({at:now(),type:'relation',delta:{affinity:Number(delta.affinity)||0,trust:Number(delta.trust)||0},reason:meta.reason||'',characterId:meta.characterId||null});save(db);return n}
function adjustFaction(factionId,amount,meta={}){const db=load(),f=ensureFaction(db,{factionId,name:meta.name});f.reputation=clamp((Number(f.reputation)||0)+(Number(amount)||0),-100,100);f.history.push({at:now(),amount:Number(amount)||0,reason:meta.reason||''});save(db);return f}
function setLocation(locationId,patch={},meta={}){const db=load(),l=ensureLocation(db,{locationId,name:meta.name});l.state={...(l.state||{}),...patch};l.history.push({at:now(),patch,reason:meta.reason||''});save(db);return l}
function commitment(data={}){const db=load(),id=data.commitmentId||uid('commit');let c=db.commitments.find(x=>x.commitmentId===id);if(!c){c={commitmentId:id,text:data.text||'',status:data.status||'pending',npcId:data.npcId||null,characterId:data.characterId||null,createdAt:now(),history:[]};db.commitments.push(c)}else if(data.status)c.status=data.status;c.history.push({at:now(),status:c.status,note:data.note||''});save(db);return c}
function addSecret(data={}){const db=load(),id=data.secretId||uid('secret');if(db.secrets.some(x=>x.secretId===id))return db.secrets.find(x=>x.secretId===id);const s={secretId:id,text:data.text||'',knownByNpcIds:data.knownByNpcIds||[],knownByCharacterIds:data.knownByCharacterIds||[],revealed:false,importance:data.importance||'critical',createdAt:now()};db.secrets.push(s);save(db);return s}
function revealSecret(secretId,characterIds=[]){const db=load(),s=db.secrets.find(x=>x.secretId===secretId);if(!s)return null;s.knownByCharacterIds=[...new Set([...(s.knownByCharacterIds||[]),...characterIds])];s.revealed=s.knownByCharacterIds.length>0;save(db);return s}
function shareFact(memoryId,characterIds=[]){const db=load(),f=db.facts.find(x=>x.memoryId===memoryId);if(!f)return null;f.characterIds=[...new Set([...(f.characterIds||[]),...characterIds])];save(db);return f}
function scoreFact(f,ctx){let s={low:1,medium:4,high:8,critical:20}[f.importance]||4;if(ctx.questId&&f.questId===ctx.questId)s+=8;if((ctx.npcIds||[]).some(id=>(f.npcIds||[]).includes(id)))s+=10;if((ctx.characterIds||[]).some(id=>(f.characterIds||[]).includes(id)))s+=5;if((ctx.factionIds||[]).some(id=>(f.factionIds||[]).includes(id)))s+=5;if((ctx.locationIds||[]).some(id=>(f.locationIds||[]).includes(id)))s+=5;return s}
function contextual(ctx={}){const db=load(),characters=window.state?.characters||[],characterIds=ctx.characterIds||characters.map(c=>c.characterId).filter(Boolean),npcIds=ctx.npcIds||[],factionIds=ctx.factionIds||[],locationIds=ctx.locationIds||[],questId=ctx.questId||window.state?.campaign?.currentQuestId||null;const cctx={characterIds,npcIds,factionIds,locationIds,questId};const facts=db.facts.filter(f=>!f.secret||f.public||characterIds.some(id=>(f.characterIds||[]).includes(id))).sort((a,b)=>scoreFact(b,cctx)-scoreFact(a,cctx)).slice(0,20).map(f=>({text:f.text,importance:f.importance,scope:f.scope}));const npcs=npcIds.map(id=>db.npcs[id]).filter(Boolean).map(n=>({npcId:n.npcId,name:n.name,role:n.role,status:n.status,previousEncounter:(n.encounters||[]).length>0,relation:{affinity:relationLabel(n.groupRelation?.affinity),trust:relationLabel(n.groupRelation?.trust)},lastEncounter:(n.encounters||[]).slice(-1)[0]||null,knownFacts:(n.knownFacts||[]).map(fid=>db.facts.find(f=>f.memoryId===fid)).filter(Boolean).filter(f=>!f.secret).slice(-8).map(f=>f.text)}));const factions=factionIds.map(id=>db.factions[id]).filter(Boolean).map(f=>({factionId:f.factionId,name:f.name,reputation:relationLabel(f.reputation)}));const commitments=db.commitments.filter(c=>c.status==='pending'&&(!c.characterId||characterIds.includes(c.characterId))&&(!c.npcId||!npcIds.length||npcIds.includes(c.npcId))).map(c=>({text:c.text,npcId:c.npcId,characterId:c.characterId,status:c.status}));return {facts,npcs,factions,commitments,rules:['Não reintroduza NPC conhecido como estranho.','Não atribua conhecimento a NPC sem acesso ao fato.','Não revele segredo não descoberto.','Relações influenciam comportamento, mas não controlam automaticamente o NPC.','Preserve consequências de encontros anteriores.']}}
function publicState(){const db=load(),chars=window.state?.characters||[];return {factions:Object.values(db.factions).map(f=>({name:f.name,state:relationLabel(f.reputation)})),npcs:Object.values(db.npcs).filter(n=>(n.encounters||[]).length).slice(-25).map(n=>({npcId:n.npcId,name:n.name,status:n.status,relation:relationLabel(n.groupRelation?.affinity),previousEncounter:true})),commitments:db.commitments.filter(c=>c.status==='pending').map(c=>({text:c.text,npcId:c.npcId,characterId:c.characterId})),characterIds:chars.map(c=>c.characterId).filter(Boolean)}}
function applyEvent(e={}){if(!e||seen(e.eventId))return {ok:false,reason:'duplicate'};let result=null;switch(e.action){case'fact':result=addFact(e);break;case'npc':result=registerNpc(e.npc||e);break;case'encounter':result=encounter(e.npcId,e);break;case'relation':result=adjustNpc(e.npcId,{affinity:e.affinity,trust:e.trust},e);break;case'faction':result=adjustFaction(e.factionId,e.amount,e);break;case'location':result=setLocation(e.locationId,e.patch||{},e);break;case'commitment':result=commitment(e);break;case'secret':result=addSecret(e);break;case'reveal-secret':result=revealSecret(e.secretId,e.characterIds||[]);break;case'share-fact':result=shareFact(e.memoryId,e.characterIds||[]);break;default:return {ok:false,reason:'unknown-action'}}if(result)mark(e.eventId);return {ok:!!result,result}}
function characterRelations(c){const db=load(),id=c?.characterId;if(!id)return[];const out=[];Object.values(db.npcs).forEach(n=>{const r=n.characterRelations?.[id];if(r)out.push({name:n.name,type:'NPC',state:relationLabel((r.affinity+r.trust)/2)})});Object.values(db.factions).forEach(f=>out.push({name:f.name,type:'Facção',state:relationLabel(f.reputation)}));return out.slice(0,12)}
const originalSheet=window.sheet;if(typeof originalSheet==='function')window.sheet=function(c){const base=originalSheet(c),rels=characterRelations(c);if(!rels.length)return base;return base+`<div class="sheet-section"><h4>Relações e Reputação</h4>${rels.map(r=>`<p><strong>${String(r.name).replace(/[&<>]/g,'')}</strong> — ${r.state}</p>`).join('')}</div>`};
window.ValeNarrativeMemory={load,save,registerNpc,encounter,addFact,adjustNpc,adjustFaction,setLocation,commitment,addSecret,revealSecret,shareFact,contextual,publicState,applyEvent,relationLabel,characterRelations,reset(){localStorage.removeItem(KEY);localStorage.removeItem(EVENT_KEY)}};
})();