// ValeDouro WEBIA — progressão por marcos + XP secundário e persistência histórica
(function(){
'use strict';
const SHEET_VERSION='VD-SHEET-V2';
const EVENT_KEY='valedouro.progression.events.v1';
const SNAPSHOT_KEY='valedouro.character.snapshots.v1';
const MAX_SNAPSHOTS=10;
const HIT_DIE={Barbaro:12,'Bárbaro':12,Guerreiro:10,Ranger:10,Patrulheiro:10,Paladino:10,'Clérigo':8,Druida:8,Monge:8,Ladino:8,Bardo:8,Bruxo:8,Feiticeiro:6,Mago:6};
const ARCANE=new Set(['Mago','Feiticeiro','Bruxo']);
const classProviders=new Map();
function uuid(){try{return 'vd-char-'+crypto.randomUUID()}catch{return 'vd-char-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)}}
function totalLevel(c){return (c.classes||[]).reduce((a,x)=>a+Math.max(0,Number(x.level)||0),0)}
function prof(level){return 2+Math.floor((Math.max(1,Number(level)||1)-1)/4)}
function conMod(c){return Math.floor(((Number(c?.attrs?.CON)||10)-10)/2)}
function ensure(c){if(!c)return null;c.characterId=c.characterId||uuid();c.sheetVersion=c.sheetVersion||SHEET_VERSION;c.status=c.status||'active';c.xp=Math.max(0,Number(c.xp)||0);c.milestones=Array.isArray(c.milestones)?c.milestones:[];c.pendingLevelUps=Math.max(0,Number(c.pendingLevelUps)||0);c.progressionHistory=Array.isArray(c.progressionHistory)?c.progressionHistory:[];c.unlockedFeatures=Array.isArray(c.unlockedFeatures)?c.unlockedFeatures:[];c.pendingChoices=Array.isArray(c.pendingChoices)?c.pendingChoices:[];c.relationships=(c.relationships&&typeof c.relationships==='object'&&!Array.isArray(c.relationships))?c.relationships:{};c.level=totalLevel(c);c.prof=prof(c.level);return c}
function characters(){return window.state?.characters||[]}
function allSaved(){try{const a=JSON.parse(localStorage.getItem('valedouro.characters')||'[]');return Array.isArray(a)?a:[]}catch{return []}}
function persist(c){if(!c)return;ensure(c);const saved=allSaved(),byId=new Map();for(const x of saved){ensure(x);byId.set(x.characterId,x)}for(const x of characters()){ensure(x);byId.set(x.characterId,x)}byId.set(c.characterId,c);localStorage.setItem('valedouro.characters',JSON.stringify([...byId.values()]));try{window.renderParty?.()}catch{}window.dispatchEvent(new CustomEvent('valedouro:progression-change',{detail:{characterId:c.characterId,name:c.name}}))}
function migrateAll(){let changed=false;const active=characters();active.forEach(c=>{if(!c.characterId||!c.sheetVersion)changed=true;ensure(c)});const saved=allSaved();saved.forEach(c=>{if(!c.characterId||!c.sheetVersion)changed=true;ensure(c)});if(changed||saved.length){const byId=new Map(saved.map(c=>[c.characterId,c]));active.forEach(c=>byId.set(c.characterId,c));localStorage.setItem('valedouro.characters',JSON.stringify([...byId.values()]))}return active}
function snapshots(){try{const x=JSON.parse(localStorage.getItem(SNAPSHOT_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return {}}}
function snapshot(c,reason='checkpoint'){ensure(c);const db=snapshots(),arr=Array.isArray(db[c.characterId])?db[c.characterId]:[];arr.unshift({at:new Date().toISOString(),reason,data:JSON.parse(JSON.stringify(c))});db[c.characterId]=arr.slice(0,MAX_SNAPSHOTS);localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(db));return db[c.characterId][0]}
function getSnapshots(c){ensure(c);return snapshots()[c.characterId]||[]}
function restoreSnapshot(c,index=0){ensure(c);const snap=getSnapshots(c)[index];if(!snap)return false;const id=c.characterId;Object.keys(c).forEach(k=>delete c[k]);Object.assign(c,JSON.parse(JSON.stringify(snap.data)),{characterId:id});ensure(c);persist(c);return true}
function seen(id){if(!id)return false;try{return JSON.parse(localStorage.getItem(EVENT_KEY)||'[]').includes(id)}catch{return false}}
function mark(id){if(!id)return;let a=[];try{a=JSON.parse(localStorage.getItem(EVENT_KEY)||'[]')}catch{};a=[...new Set([...a,id])].slice(-1000);localStorage.setItem(EVENT_KEY,JSON.stringify(a))}
function history(c,type,data={}){ensure(c);c.progressionHistory.unshift({at:new Date().toISOString(),type,...data});c.progressionHistory=c.progressionHistory.slice(0,200)}
function grantXP(c,amount,reason='',eventId){ensure(c);amount=Math.max(0,Math.floor(Number(amount)||0));if(eventId&&seen(eventId))return {ok:false,reason:'duplicate'};c.xp+=amount;history(c,'xp',{amount,reason,xp:c.xp});if(eventId)mark(eventId);persist(c);return {ok:true,xp:c.xp,amount}}
function grantMilestone(c,label,opts={}){ensure(c);const eventId=opts.eventId;if(eventId&&seen(eventId))return {ok:false,reason:'duplicate'};const m={id:opts.id||`milestone-${Date.now()}`,label:label||'Marco narrativo',questId:opts.questId||window.ValeDouroCampaign?.read?.()?.currentQuestId||null,at:new Date().toISOString(),levelUp:opts.levelUp!==false};c.milestones.push(m);if(m.levelUp)c.pendingLevelUps+=Math.max(1,Number(opts.levels)||1);history(c,'milestone',{label:m.label,questId:m.questId,levelUp:m.levelUp,pendingLevelUps:c.pendingLevelUps});if(eventId)mark(eventId);snapshot(c,'marco: '+m.label);persist(c);return {ok:true,milestone:m,pendingLevelUps:c.pendingLevelUps}}
function classEntry(c,className){return (c.classes||[]).find(x=>x.name===className)}
function availableClasses(c){return (c.classes||[]).map(x=>x.name)}
function hpGain(c,className,method='average'){const die=HIT_DIE[className]||8,cm=conMod(c);const rolled=method==='roll'?Math.floor(Math.random()*die)+1:Math.floor(die/2)+1;return {die,rolled,conModifier:cm,gain:Math.max(1,rolled+cm),method}}
function classUnlocks(c,className,newClassLevel){const fn=classProviders.get(className);if(!fn)return [];try{const out=fn({character:c,className,classLevel:newClassLevel,totalLevel:totalLevel(c)});return Array.isArray(out)?out:[]}catch(e){console.warn('Progressão de classe não pôde ser aplicada',e);return []}}
function registerClassProgression(className,provider){if(className&&typeof provider==='function')classProviders.set(className,provider)}
function performLevelUp(c,className,opts={}){ensure(c);if(c.pendingLevelUps<1)return {ok:false,reason:'not-available'};let ce=classEntry(c,className);if(!ce){if(!opts.allowNewClass)return {ok:false,reason:'class-not-found'};ce={name:className,level:0};c.classes.push(ce)}if(totalLevel(c)>=20)return {ok:false,reason:'max-level'};snapshot(c,'antes do level up');const before={totalLevel:totalLevel(c),classLevel:Number(ce.level)||0,hpMax:Number(c.hpMax)||1,hp:Number(c.hp)||0,manaMax:c.manaMax??null,prof:c.prof};const hp=hpGain(c,className,opts.hpMethod==='roll'?'roll':'average');ce.level=(Number(ce.level)||0)+1;c.level=totalLevel(c);c.prof=prof(c.level);c.cls=(c.classes||[]).map(x=>`${x.name} ${x.level}`).join(' / ');c.hpMax=Math.max(1,before.hpMax+hp.gain);c.hp=Math.min(c.hpMax,Math.max(0,before.hp)+hp.gain);let manaRolls=null;if(ARCANE.has(className)&&window.ValeMana?.levelUp&&c.manaMax!=null)manaRolls=window.ValeMana.levelUp(c,1);const unlocks=classUnlocks(c,className,ce.level);for(const u of unlocks){const item=typeof u==='string'?{id:`${className}-${ce.level}-${u}`,name:u}:u;if(item?.id&&!c.unlockedFeatures.some(x=>x.id===item.id))c.unlockedFeatures.push({...item,className,classLevel:ce.level,unlockedAt:new Date().toISOString()});if(item?.choice)c.pendingChoices.push({...item.choice,className,classLevel:ce.level,createdAt:new Date().toISOString()})}c.pendingLevelUps-=1;const entry={fromLevel:before.totalLevel,toLevel:c.level,className,classLevel:ce.level,hpGain:hp,hpMaxBefore:before.hpMax,hpMaxAfter:c.hpMax,manaGain:manaRolls||null,profBefore:before.prof,profAfter:c.prof,questId:window.ValeDouroCampaign?.read?.()?.currentQuestId||null};history(c,'level-up',entry);snapshot(c,'depois do level up');persist(c);return {ok:true,...entry,pendingLevelUps:c.pendingLevelUps}}
function setStatus(c,status){ensure(c);if(!['active','deceased','retired'].includes(status))return false;c.status=status;history(c,'status',{status});snapshot(c,'status: '+status);persist(c);return true}
function setRelationship(c,key,value){ensure(c);c.relationships[key]=value;history(c,'relationship',{key,value});persist(c);return true}
function resolveChoice(c,index,value){ensure(c);const p=c.pendingChoices[index];if(!p)return false;p.resolved=true;p.value=value;p.resolvedAt=new Date().toISOString();history(c,'choice',{choice:p.id||p.label||'choice',value});persist(c);return true}
function publicState(){return characters().map(c=>{ensure(c);return {characterId:c.characterId,name:c.name,status:c.status,sheetVersion:c.sheetVersion,totalLevel:c.level,classes:c.classes,xp:c.xp,milestones:c.milestones.map(m=>({label:m.label,questId:m.questId,levelUp:m.levelUp})),pendingLevelUps:c.pendingLevelUps,unlockedFeatures:c.unlockedFeatures.map(x=>({id:x.id,name:x.name,className:x.className,classLevel:x.classLevel})),pendingChoices:c.pendingChoices.filter(x=>!x.resolved),relationships:c.relationships}})}
function applyEvent(c,e){ensure(c);if(!e||!c)return {ok:false,reason:'invalid'};if(e.eventId&&seen(e.eventId))return {ok:false,reason:'duplicate'};if(e.action==='xp')return grantXP(c,e.amount,e.reason||'',e.eventId);if(e.action==='milestone')return grantMilestone(c,e.label||e.reason||'Marco narrativo',{...e,eventId:e.eventId});if(e.action==='status'){const ok=setStatus(c,e.status);if(ok&&e.eventId)mark(e.eventId);return {ok}}if(e.action==='relationship'){const ok=setRelationship(c,e.key,e.value);if(ok&&e.eventId)mark(e.eventId);return {ok}}return {ok:false,reason:'unsupported'}}
function esc(s){return window.esc?window.esc(String(s??'')):String(s??'')}
function progressionBlock(c){ensure(c);const last=c.progressionHistory.find(x=>x.type==='level-up');return `<div class="sheet-section progression-section"><h4>Progressão</h4><div class="stat-grid"><div class="stat">Nível<b>${c.level}</b></div><div class="stat">XP<b>${c.xp}</b></div><div class="stat">Marcos<b>${c.milestones.length}</b></div><div class="stat">Progressões<b>${c.pendingLevelUps}</b></div></div><p class="muted">ID: ${esc(c.characterId)} • ${esc(c.sheetVersion)} • status: ${esc(c.status)}</p>${last?`<p><strong>Última progressão:</strong> ${esc(last.className)} ${last.classLevel} • HP +${last.hpGain?.gain||0}</p>`:''}${c.pendingLevelUps>0?`<button class="btn primary no-print" onclick="ValeProgression.openLevelUp('${esc(c.characterId)}')">REALIZAR PROGRESSÃO</button>`:''}</div>`}
function findById(id){return characters().find(c=>(ensure(c),c.characterId===id))||allSaved().find(c=>(ensure(c),c.characterId===id))}
function openLevelUp(id){const c=findById(id);if(!c||c.pendingLevelUps<1)return;let modal=document.getElementById('progressionModal');if(!modal){modal=document.createElement('div');modal.id='progressionModal';modal.className='modal';modal.innerHTML='<div class="panel sheet"><div class="row" style="justify-content:space-between"><h2>Progressão de personagem</h2><button class="btn" onclick="ValeProgression.closeLevelUp()">Fechar</button></div><div id="progressionContent"></div></div>';document.body.appendChild(modal)}const classes=availableClasses(c);document.getElementById('progressionContent').innerHTML=`<h3>${esc(c.name)}</h3><p>Nível atual ${c.level}. Progressões disponíveis: <strong>${c.pendingLevelUps}</strong>.</p><div class="field"><label>Classe que receberá o nível</label><select id="progressionClass">${classes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Ganho de HP</label><select id="progressionHP"><option value="average">Valor médio fixo</option><option value="roll">Rolar dado de vida</option></select></div><p class="muted">Ferimentos existentes não são removidos. Mana cresce somente se a classe escolhida for arcana.</p><button class="btn primary" onclick="ValeProgression.confirmLevelUp('${esc(c.characterId)}')">CONFIRMAR PROGRESSÃO</button><div id="progressionResult"></div>`;modal.classList.add('active')}
function closeLevelUp(){document.getElementById('progressionModal')?.classList.remove('active')}
function confirmLevelUp(id){const c=findById(id),className=document.getElementById('progressionClass')?.value,hpMethod=document.getElementById('progressionHP')?.value||'average',r=performLevelUp(c,className,{hpMethod});const out=document.getElementById('progressionResult');if(!out)return;if(!r.ok){out.innerHTML=`<p class="fail">Não foi possível realizar a progressão: ${esc(r.reason)}</p>`;return}out.innerHTML=`<p class="pass"><strong>Progressão concluída.</strong> ${esc(r.className)} ${r.classLevel}; HP +${r.hpGain.gain}; nível total ${r.toLevel}; proficiência ${r.profAfter>=0?'+':''}${r.profAfter}.${r.manaGain?` Mana +${r.manaGain.reduce((a,x)=>a+x.gain,0)}.`:''}</p>`;try{const i=characters().indexOf(c);if(i>=0&&window.openSheet){setTimeout(()=>window.openSheet(i),150)}}catch{}}
function patchSheet(){const base=window.sheet;if(typeof base==='function'&&!base.__valeProgression){const wrapped=function(c){ensure(c);return base(c)+progressionBlock(c)};wrapped.__valeProgression=true;window.sheet=wrapped}const open=window.openSheet;if(typeof open==='function'&&!open.__valeProgression){const wrappedOpen=function(i){const c=window.state?.characters?.[i];if(c)ensure(c);const r=open.apply(this,arguments);const target=document.getElementById('sheetContent');if(target&&c&&!target.querySelector('.progression-section'))target.insertAdjacentHTML('beforeend',progressionBlock(c));return r};wrappedOpen.__valeProgression=true;window.openSheet=wrappedOpen}}
window.ValeProgression={SHEET_VERSION,HIT_DIE,ensure,migrateAll,snapshot,getSnapshots,restoreSnapshot,grantXP,grantMilestone,performLevelUp,registerClassProgression,setStatus,setRelationship,resolveChoice,publicState,applyEvent,progressionBlock,openLevelUp,closeLevelUp,confirmLevelUp};
window.addEventListener('DOMContentLoaded',()=>{migrateAll();setTimeout(patchSheet,50)});setTimeout(()=>{migrateAll();patchSheet()},100);
})();