// ValeDouro WEBIA — magias arcanas, divinas e naturais
(function(){
'use strict';
const EVENT_KEY='valedouro.spells.events.v1';
let catalog={version:1,spells:[]};
const ARCANE=new Set(['Mago','Feiticeiro','Bruxo']);
function chars(){return window.state?.characters||[]}
function ensure(c){if(!c)return null;c.spellState=(c.spellState&&typeof c.spellState==='object'&&!Array.isArray(c.spellState))?c.spellState:{};c.spellState.known=Array.isArray(c.spellState.known)?c.spellState.known:[];c.spellState.prepared=Array.isArray(c.spellState.prepared)?c.spellState.prepared:[];c.spellState.concentration=c.spellState.concentration||null;c.spellState.history=Array.isArray(c.spellState.history)?c.spellState.history:[];return c}
function seen(id){if(!id)return false;try{return JSON.parse(localStorage.getItem(EVENT_KEY)||'[]').includes(id)}catch{return false}}
function mark(id){if(!id)return;let a=[];try{a=JSON.parse(localStorage.getItem(EVENT_KEY)||'[]')}catch{};a=[...new Set([...a,id])].slice(-1000);localStorage.setItem(EVENT_KEY,JSON.stringify(a))}
function persist(c){ensure(c);try{window.saveChars?.()}catch{};window.dispatchEvent(new CustomEvent('valedouro:spells-change',{detail:{characterId:c.characterId,name:c.name}}))}
function levelOf(c,name){return (c.classes||[]).filter(x=>x.name===name).reduce((a,x)=>a+(Number(x.level)||0),0)}
function arcaneLevel(c){return (c.classes||[]).filter(x=>ARCANE.has(x.name)).reduce((a,x)=>a+(Number(x.level)||0),0)}
function maxCircle(c,tradition){if(tradition==='arcane'){const l=arcaneLevel(c);return l?Math.min(9,Math.ceil(l/2)):-1}if(tradition==='divine'){const cleric=levelOf(c,'Clérigo'),paladin=levelOf(c,'Paladino');return Math.max(cleric?Math.ceil(cleric/2):-1,paladin>=2?Math.ceil(paladin/4):-1)}if(tradition==='natural'){const druid=levelOf(c,'Druida'),ranger=Math.max(levelOf(c,'Ranger'),levelOf(c,'Patrulheiro'));return Math.max(druid?Math.ceil(druid/2):-1,ranger>=2?Math.ceil(ranger/4):-1)}return -1}
function traditions(c){return ['arcane','divine','natural'].filter(t=>maxCircle(c,t)>=0)}
function byId(id){return catalog.spells.find(s=>s.id===id)||null}
function eligible(c,s){if(maxCircle(c,s.tradition)<Number(s.circle))return false;return (s.classes||[]).some(name=>(c.classes||[]).some(x=>x.name===name))}
function reconcile(c){ensure(c);const starter=catalog.spells.filter(s=>eligible(c,s));for(const s of starter){if(!c.spellState.known.includes(s.id)){c.spellState.known.push(s.id);c.spellState.prepared.push(s.id)}}c.spellState.known=c.spellState.known.filter(id=>!!byId(id));c.spellState.prepared=c.spellState.prepared.filter(id=>c.spellState.known.includes(id));persist(c);return c}
function reconcileAll(){chars().forEach(reconcile);return chars()}
async function loadCatalog(){try{const r=await fetch('data/spells.json',{cache:'no-store'});if(r.ok)catalog=await r.json()}catch(e){console.warn('Catálogo de magias indisponível',e)}reconcileAll();return catalog}
function learn(c,id){ensure(c);const s=byId(id);if(!s||!eligible(c,s))return false;if(!c.spellState.known.includes(id))c.spellState.known.push(id);persist(c);return true}
function prepare(c,id,on=true){ensure(c);if(!c.spellState.known.includes(id))return false;if(on&&!c.spellState.prepared.includes(id))c.spellState.prepared.push(id);if(!on)c.spellState.prepared=c.spellState.prepared.filter(x=>x!==id);persist(c);return true}
function hasMaterial(c,component){if(typeof component!=='object'||!component.itemId)return true;const inv=window.ValeInventory?.ensure?.(c);if(!inv)return false;const items=[...(inv.items||[]),...(inv.resources||[])];const it=items.find(x=>x.id===component.itemId);return !!it&&Number(it.qty)>=Number(component.qty||1)}
function consumeMaterials(c,s){for(const comp of s.components||[]){if(typeof comp==='object'&&comp.itemId&&comp.consumed!==false){if(!window.ValeInventory?.consume?.(c,comp.itemId,Number(comp.qty||1)))return false}}return true}
function manaCost(s){return s.tradition==='arcane'?(window.ValeMana?.spellCost?.(Number(s.circle))??0):0}
function canCast(c,id){ensure(c);const s=byId(id);if(!s)return {ok:false,reason:'unknown-spell'};if(!eligible(c,s))return {ok:false,reason:'class-access'};if(!c.spellState.known.includes(id))return {ok:false,reason:'not-known'};if(!c.spellState.prepared.includes(id))return {ok:false,reason:'not-prepared'};for(const comp of s.components||[]){if(!hasMaterial(c,comp))return {ok:false,reason:'missing-component',component:comp}}const cost=manaCost(s);if(s.tradition==='arcane'&&Number(c.mana||0)<cost)return {ok:false,reason:'insufficient-mana',cost,mana:c.mana||0};return {ok:true,spell:s,cost}}
function cast(c,id,eventId){if(eventId&&seen(eventId))return {ok:false,reason:'duplicate'};const check=canCast(c,id);if(!check.ok)return check;const s=check.spell;if(!consumeMaterials(c,s))return {ok:false,reason:'component-consume-failed'};if(s.tradition==='arcane'&&check.cost>0){const paid=window.ValeMana?.spend?.(c,check.cost);if(!paid?.ok)return {ok:false,reason:paid?.reason||'mana-failed'}}const previous=c.spellState.concentration;if(s.concentration)c.spellState.concentration={spellId:s.id,name:s.name,startedAt:new Date().toISOString()};c.spellState.history.unshift({at:new Date().toISOString(),type:'cast',spellId:id,cost:check.cost,previousConcentration:previous?.spellId||null});c.spellState.history=c.spellState.history.slice(0,120);if(eventId)mark(eventId);persist(c);return {ok:true,spell:s.name,cost:check.cost,concentration:c.spellState.concentration,endedConcentration:s.concentration?previous:null,healingPolicy:healingPolicy(s)}}
function endConcentration(c,reason='ended',eventId){ensure(c);if(eventId&&seen(eventId))return {ok:false,reason:'duplicate'};const old=c.spellState.concentration;if(!old)return {ok:false,reason:'none'};c.spellState.concentration=null;c.spellState.history.unshift({at:new Date().toISOString(),type:'concentration-end',spellId:old.spellId,reason});if(eventId)mark(eventId);persist(c);return {ok:true,spell:old,reason}}
function healingPolicy(s){return (s.tags||[]).includes('healing')?{functionalHp:true,stabilization:true,structuralHealing:false,canRestoreAmputation:false,canInstantlyRepairFracture:false}:null}
function known(c){ensure(c);return c.spellState.known.map(byId).filter(Boolean)}
function publicState(){return chars().map(c=>{reconcile(c);return {characterId:c.characterId,name:c.name,traditions:traditions(c),known:known(c).map(s=>({id:s.id,name:s.name,circle:s.circle,tradition:s.tradition,cost:manaCost(s),prepared:c.spellState.prepared.includes(s.id),concentration:s.concentration,healingPolicy:healingPolicy(s)})),concentration:c.spellState.concentration}})}
function applyEvent(c,e){if(!c||!e)return {ok:false,reason:'invalid'};if(e.eventId&&seen(e.eventId))return {ok:false,reason:'duplicate'};if(e.action==='cast')return cast(c,e.spellId,e.eventId);if(e.action==='concentration-end')return endConcentration(c,e.reason||'ended',e.eventId);if(e.action==='learn'){const ok=learn(c,e.spellId);if(ok&&e.eventId)mark(e.eventId);return {ok}}if(e.action==='prepare'){const ok=prepare(c,e.spellId,e.prepared!==false);if(ok&&e.eventId)mark(e.eventId);return {ok}}return {ok:false,reason:'unsupported'}}
function esc(s){return window.esc?window.esc(String(s??'')):String(s??'')}
function idxOf(c){return chars().indexOf(c)}
function uiCast(i,id){const c=chars()[i],r=cast(c,id,`ui-spell-${c?.characterId}-${id}-${Date.now()}`);if(!r.ok)alert(`Não foi possível lançar a magia: ${r.reason}.`);try{window.openSheet?.(i)}catch{}}
function uiPrepare(i,id,on){const c=chars()[i];prepare(c,id,on);try{window.openSheet?.(i)}catch{}}
function uiEndConcentration(i){const c=chars()[i];endConcentration(c,'encerrada pelo jogador',`ui-concentration-${c?.characterId}-${Date.now()}`);try{window.openSheet?.(i)}catch{}}
function block(c){reconcile(c);const ks=known(c),i=idxOf(c);if(!ks.length)return '';return `<div class="sheet-section spell-section"><h4>Magias</h4><p><strong>Tradições:</strong> ${traditions(c).map(esc).join(', ')||'—'}${c.spellState.concentration?` • <strong>Concentração:</strong> ${esc(c.spellState.concentration.name)}${i>=0?` <button class="btn small no-print" onclick="ValeSpells.uiEndConcentration(${i})">Encerrar</button>`:''}`:''}</p>${ks.map(s=>{const prepared=c.spellState.prepared.includes(s.id),castable=canCast(c,s.id).ok;return `<p><strong>${esc(s.name)}</strong> — círculo ${s.circle} • ${esc(s.tradition)}${s.tradition==='arcane'?` • Mana ${manaCost(s)}`:''}${s.concentration?' • concentração':''}<br><span class="muted">${esc(s.effect)}</span>${i>=0?`<br><button class="btn small no-print" ${castable?'':'disabled'} onclick="ValeSpells.uiCast(${i},'${esc(s.id)}')">Lançar</button> <button class="btn small no-print" onclick="ValeSpells.uiPrepare(${i},'${esc(s.id)}',${prepared?'false':'true'})">${prepared?'Despreparar':'Preparar'}</button>`:''}</p>`}).join('')}</div>`}
function patchSheet(){const base=window.sheet;if(typeof base==='function'&&!base.__valeSpells){const wrapped=function(c){return base(c)+block(c)};wrapped.__valeSpells=true;window.sheet=wrapped}const open=window.openSheet;if(typeof open==='function'&&!open.__valeSpells){const wrapped=function(i){const c=window.state?.characters?.[i];const r=open.apply(this,arguments);const t=document.getElementById('sheetContent');if(c&&t&&!t.querySelector('.spell-section'))t.insertAdjacentHTML('beforeend',block(c));return r};wrapped.__valeSpells=true;window.openSheet=wrapped}}
window.ValeSpells={loadCatalog,reconcile,reconcileAll,traditions,maxCircle,learn,prepare,canCast,cast,endConcentration,known,healingPolicy,publicState,applyEvent,block,uiCast,uiPrepare,uiEndConcentration};
window.addEventListener('DOMContentLoaded',()=>{loadCatalog();setTimeout(patchSheet,100)});window.addEventListener('valedouro:progression-change',e=>{const c=chars().find(x=>x.characterId===e.detail?.characterId);if(c)reconcile(c)});setTimeout(()=>{loadCatalog();patchSheet()},180);
})();