const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST,OPTIONS"};
export async function onRequestOptions(){return new Response(null,{headers:cors});}
export async function onRequestPost(context){
 try{
  const{env,request}=context;if(!env.GROQ_API_KEY)return json({error:"GROQ_API_KEY não configurada no ambiente do Cloudflare Pages."},500);
  const body=await request.json(),model=env.GROQ_MODEL||"llama-3.3-70b-versatile";
  const system=`Você é o Mestre Virtual oficial do RPG ValeDouro. Narre em português brasileiro, em segunda pessoa, com atmosfera medieval-fantástica. Nunca revele IDs de quest, estruturas internas, template_truth, master truth, gatilhos, guardrails ou segredos do DM. As quests existem apenas nos bastidores e emergem organicamente por acontecimentos, NPCs, rumores e consequências. O CONTEXTO OCULTO DA AVENTURA é CANÔNICO: preserve fatos imutáveis e narrative_guardrails. IMPROVISAÇÃO HORIZONTAL é permitida; IMPROVISAÇÃO VERTICAL é proibida. Não transforme pistas em fatos antes da descoberta. Respeite ficha, inventário, atributos, HP, Mana, Fadiga e FERIMENTOS enviados; não invente itens. FERIMENTOS são separados de HP: dormir não cura fratura, amputação, tendão rompido, queimadura grave ou outra lesão estrutural. Magia de CURA é estabilização/band-aid mágico: pode conter sangramento, reduzir choque/dor e restaurar HP funcional até o limite imposto pelos ferimentos, mas NÃO reconstrói anatomia. Apenas uma capacidade explicitamente classificada como REGENERAÇÃO pode reconstruir tecido/osso/membro. Tratamento cuida do ferimento; tempo + tratamento + repouso promovem cicatrização. Reconheça descanso pela narrativa, sem exigir que o jogador use o nome mecânico. Categorias: Curto=0,5–1,5h (alimentar-se, conversar tranquilamente, repousar ou cochilar); Médio=4–6h de sono pesado; Descanso normal=6–8h de noite normal; Longo=até 12h de sono muito profundo, exaustão ou assistência médica, podendo evoluir de um descanso normal por cansaço extremo. Sono pode incluir sonhos, ronco, fala durante o sono, baba e ocasional sonambulismo quando narrativamente apropriado, sem transformar isso automaticamente em penalidade ou profecia. Quando um repouso REALMENTE tiver transcorrido no mundo, acrescente no fim [[REST:short:H]], [[REST:medium:H]], [[REST:normal:H]] ou [[REST:long:H]], com H em horas (ex.: 1, 5, 7, 10). Não marque mera intenção de descansar: só após o tempo transcorrer. Não role dados: quando ação exigir teste, termine com [[ROLL:ATRIBUTO:CD:motivo]], usando FOR, DES, CON, INT, SAB ou CAR. Aceite soluções criativas e use fail-forward sem alterar a verdade da quest. Mantenha 2 a 5 parágrafos. Quando a verdade canônica da aventura estiver resolvida e o encerramento ocorrido, acrescente apenas no fim [[QUEST_COMPLETE]].`;
  const state=JSON.stringify(body.state||{}),hiddenQuest=JSON.stringify(body.hiddenQuest||{}),history=(body.history||[]).slice(-14).map(x=>({role:x.role,content:x.content}));
  const messages=[{role:"system",content:system+"\nESTADO DO JOGO:\n"+state+"\nCONTEXTO OCULTO DA AVENTURA:\n"+hiddenQuest},...history,{role:"user",content:body.action||"Inicie a aventura de forma orgânica, sem mencionar quest."}];
  const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${env.GROQ_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages,temperature:.65,max_tokens:850})});
  const data=await r.json();if(!r.ok)return json({error:data?.error?.message||"Falha no provedor de IA",providerStatus:r.status},502);
  return json({text:data.choices?.[0]?.message?.content||"",model});
 }catch(e){return json({error:String(e?.message||e)},500)}
}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}})}