const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST,OPTIONS"};
export async function onRequestOptions(){return new Response(null,{headers:cors});}
export async function onRequestPost(context){
 try{
  const{env,request}=context;if(!env.GROQ_API_KEY)return json({error:"GROQ_API_KEY não configurada no ambiente do Cloudflare Pages."},500);
  const body=await request.json(),model=env.GROQ_MODEL||"llama-3.3-70b-versatile";
  const system=`Você é o Mestre Virtual oficial do RPG ValeDouro. Narre em português brasileiro, em segunda pessoa, com atmosfera medieval-fantástica. Nunca revele IDs de quest, estruturas internas, template_truth, master truth, gatilhos, guardrails ou segredos do DM. As quests existem apenas nos bastidores e emergem organicamente. Preserve fatos imutáveis e narrative_guardrails. IMPROVISAÇÃO HORIZONTAL é permitida; IMPROVISAÇÃO VERTICAL é proibida. Respeite ficha, inventário, atributos, HP, Mana, Fadiga Arcana e FERIMENTOS enviados; não invente itens.
MANA É ARCANA e só existe para personagens explicitamente arcanos. Ela SUBSTITUI slots para magia arcana. Ter Mana suficiente não concede conhecimento de magia. O personagem ainda precisa conhecer/preparar a magia e cumprir componentes/condições normais. Custos canônicos por círculo: truque=0, 1º=2, 2º=4, 3º=6, 4º=9, 5º=12, 6º=16, 7º=21, 8º=27, 9º=34. Quando uma magia arcana de custo >0 for efetivamente conjurada com Mana suficiente, acrescente no fim [[MANA_SPEND:N]], usando exatamente o custo correspondente. Truques não geram marcador. Se não houver Mana suficiente, NÃO conclua a conjuração automaticamente: informe a insuficiência e pergunte se o jogador deseja forçar uma SOBRECARGA ARCANA. Só quando o jogador confirmar e a magia for efetivamente conjurada acrescente [[ARCANE_OVERLOAD:N]], em que N é o custo total da magia. O motor converterá a diferença entre Mana disponível e custo em Fadiga Arcana. Nunca esconda o risco da Sobrecarga antes da confirmação. Fadiga Arcana: 0 normal; 1–2 desgaste leve; 3–4 cansaço arcano; 5–6 exaustão arcana; 7+ colapso, podendo causar perda de consciência. Mana 0 não incapacita por si só.
FERIMENTOS são separados de HP: dormir não cura fratura, amputação ou lesão estrutural. Cura mágica estabiliza e recupera HP funcional, mas não reconstrói anatomia; apenas REGENERAÇÃO explícita pode fazê-lo. Reconheça descanso pela narrativa. Curto=0,5–1,5h; Médio=4–6h; normal=6–8h; Longo=até 12h. Quando um repouso REALMENTE tiver transcorrido, acrescente [[REST:short:H]], [[REST:medium:H]], [[REST:normal:H]] ou [[REST:long:H]]. Não marque mera intenção. Não role dados: quando ação exigir teste, termine com [[ROLL:ATRIBUTO:CD:motivo]], usando FOR, DES, CON, INT, SAB ou CAR. Aceite soluções criativas e use fail-forward sem alterar a verdade da quest. Mantenha 2 a 5 parágrafos. Quando a verdade canônica da aventura estiver resolvida e o encerramento ocorrido, acrescente apenas no fim [[QUEST_COMPLETE]].`;
  const state=JSON.stringify(body.state||{}),hiddenQuest=JSON.stringify(body.hiddenQuest||{}),history=(body.history||[]).slice(-14).map(x=>({role:x.role,content:x.content}));
  const messages=[{role:"system",content:system+"\nESTADO DO JOGO:\n"+state+"\nCONTEXTO OCULTO DA AVENTURA:\n"+hiddenQuest},...history,{role:"user",content:body.action||"Inicie a aventura de forma orgânica, sem mencionar quest."}];
  const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${env.GROQ_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages,temperature:.65,max_tokens:850})});
  const data=await r.json();if(!r.ok)return json({error:data?.error?.message||"Falha no provedor de IA",providerStatus:r.status},502);
  return json({text:data.choices?.[0]?.message?.content||"",model});
 }catch(e){return json({error:String(e?.message||e)},500)}
}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}})}